; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -march=sbf | FileCheck %s

; test that we can expand CTTZ & CTLZ

declare i32 @llvm.cttz.i32(i32, i1)

define i32 @cttz_i32_zdef(i32 %a) {
; CHECK-LABEL: cttz_i32_zdef:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    neg64 r2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    mul64 r1, 125613361
; CHECK-NEXT:    lddw r2, 4160749568
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    rsh64 r1, 27
; CHECK-NEXT:    lddw r2, {{\.?LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    add64 r2, r1
; CHECK-NEXT:    ldxb r0, [r2 + 0]
; CHECK-NEXT:    exit
    %ret = call i32 @llvm.cttz.i32(i32 %a, i1 1)
    ret i32 %ret
}


define i32 @cttz_i32(i32 %a) {
; CHECK-LABEL: cttz_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    lsh64 r2, 32
; CHECK-NEXT:    rsh64 r2, 32
; CHECK-NEXT:    jeq r2, 0, LBB1_1
; CHECK-NEXT:  # %bb.2: # %cond.false
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    neg64 r2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    mul64 r1, 125613361
; CHECK-NEXT:    lddw r2, 4160749568
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    rsh64 r1, 27
; CHECK-NEXT:    lddw r2, {{\.?LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    add64 r2, r1
; CHECK-NEXT:    ldxb r0, [r2 + 0]
; CHECK-NEXT:    ja LBB1_3
; CHECK-NEXT:  LBB1_1:
; CHECK-NEXT:    mov64 r0, 32
; CHECK-NEXT:  LBB1_3: # %cond.end
; CHECK-NEXT:    exit
    %ret = call i32 @llvm.cttz.i32(i32 %a, i1 0)
    ret i32 %ret
}

declare i64 @llvm.cttz.i64(i64, i1)

define i64 @cttz_i64_zdef(i64 %a) {
; CHECK-LABEL: cttz_i64_zdef:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    neg64 r2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    lddw r2, 151050438420815295
; CHECK-NEXT:    mul64 r1, r2
; CHECK-NEXT:    rsh64 r1, 58
; CHECK-NEXT:    lddw r2, {{\.?LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    add64 r2, r1
; CHECK-NEXT:    ldxb r0, [r2 + 0]
; CHECK-NEXT:    exit
    %ret = call i64 @llvm.cttz.i64(i64 %a, i1 1)
    ret i64 %ret
}


define i64 @cttz_i64(i64 %a) {
; CHECK-LABEL: cttz_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jeq r1, 0, LBB3_1
; CHECK-NEXT:  # %bb.2: # %cond.false
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    neg64 r2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    lddw r2, 151050438420815295
; CHECK-NEXT:    mul64 r1, r2
; CHECK-NEXT:    rsh64 r1, 58
; CHECK-NEXT:    lddw r2, {{\.?LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    add64 r2, r1
; CHECK-NEXT:    ldxb r0, [r2 + 0]
; CHECK-NEXT:    ja LBB3_3
; CHECK-NEXT:  LBB3_1:
; CHECK-NEXT:    mov64 r0, 64
; CHECK-NEXT:  LBB3_3: # %cond.end
; CHECK-NEXT:    exit
    %ret = call i64 @llvm.cttz.i64(i64 %a, i1 0)
    ret i64 %ret
}


declare i32 @llvm.ctlz.i32(i32, i1)

define i32 @ctlz_i32_zdef(i32 %a) {
; CHECK-LABEL: ctlz_i32_zdef:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lddw r2, 4294967294
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 1
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967292
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 2
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967280
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 4
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967040
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 8
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294901760
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 16
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    xor64 r1, -1
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 1
; CHECK-NEXT:    and64 r2, 1431655765
; CHECK-NEXT:    sub64 r1, r2
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    and64 r0, 858993459
; CHECK-NEXT:    rsh64 r1, 2
; CHECK-NEXT:    and64 r1, 858993459
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    mov64 r1, r0
; CHECK-NEXT:    rsh64 r1, 4
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    and64 r0, 252645135
; CHECK-NEXT:    mul64 r0, 16843009
; CHECK-NEXT:    lddw r1, 4278190080
; CHECK-NEXT:    and64 r0, r1
; CHECK-NEXT:    rsh64 r0, 24
; CHECK-NEXT:    exit
    %ret = call i32 @llvm.ctlz.i32(i32 %a, i1 1)
    ret i32 %ret
}


define i32 @ctlz_i32(i32 %a) {
; CHECK-LABEL: ctlz_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    lsh64 r2, 32
; CHECK-NEXT:    rsh64 r2, 32
; CHECK-NEXT:    jeq r2, 0, LBB5_1
; CHECK-NEXT:  # %bb.2: # %cond.false
; CHECK-NEXT:    lddw r2, 4294967294
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 1
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967292
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 2
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967280
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 4
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294967040
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 8
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    lddw r2, 4294901760
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    rsh64 r3, 16
; CHECK-NEXT:    or64 r1, r3
; CHECK-NEXT:    xor64 r1, -1
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 1
; CHECK-NEXT:    and64 r2, 1431655765
; CHECK-NEXT:    sub64 r1, r2
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    and64 r0, 858993459
; CHECK-NEXT:    rsh64 r1, 2
; CHECK-NEXT:    and64 r1, 858993459
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    mov64 r1, r0
; CHECK-NEXT:    rsh64 r1, 4
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    and64 r0, 252645135
; CHECK-NEXT:    mul64 r0, 16843009
; CHECK-NEXT:    lddw r1, 4278190080
; CHECK-NEXT:    and64 r0, r1
; CHECK-NEXT:    rsh64 r0, 24
; CHECK-NEXT:    ja LBB5_3
; CHECK-NEXT:  LBB5_1:
; CHECK-NEXT:    mov64 r0, 32
; CHECK-NEXT:  LBB5_3: # %cond.end
; CHECK-NEXT:    exit
    %ret = call i32 @llvm.ctlz.i32(i32 %a, i1 0)
    ret i32 %ret
}

declare i64 @llvm.ctlz.i64(i64, i1)

define i64 @ctlz_i64_zdef(i64 %a) {
; CHECK-LABEL: ctlz_i64_zdef:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 1
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 2
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 4
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 8
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 16
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 32
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    xor64 r1, -1
; CHECK-NEXT:    lddw r2, 6148914691236517205
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    rsh64 r3, 1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    sub64 r1, r3
; CHECK-NEXT:    lddw r2, 3689348814741910323
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    and64 r0, r2
; CHECK-NEXT:    rsh64 r1, 2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    mov64 r1, r0
; CHECK-NEXT:    rsh64 r1, 4
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    lddw r1, 1085102592571150095
; CHECK-NEXT:    and64 r0, r1
; CHECK-NEXT:    lddw r1, 72340172838076673
; CHECK-NEXT:    mul64 r0, r1
; CHECK-NEXT:    rsh64 r0, 56
; CHECK-NEXT:    exit
    %ret = call i64 @llvm.ctlz.i64(i64 %a, i1 1)
    ret i64 %ret
}


define i64 @ctlz_i64(i64 %a) {
; CHECK-LABEL: ctlz_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jeq r1, 0, LBB7_1
; CHECK-NEXT:  # %bb.2: # %cond.false
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 1
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 2
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 4
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 8
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 16
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    mov64 r2, r1
; CHECK-NEXT:    rsh64 r2, 32
; CHECK-NEXT:    or64 r1, r2
; CHECK-NEXT:    xor64 r1, -1
; CHECK-NEXT:    lddw r2, 6148914691236517205
; CHECK-NEXT:    mov64 r3, r1
; CHECK-NEXT:    rsh64 r3, 1
; CHECK-NEXT:    and64 r3, r2
; CHECK-NEXT:    sub64 r1, r3
; CHECK-NEXT:    lddw r2, 3689348814741910323
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    and64 r0, r2
; CHECK-NEXT:    rsh64 r1, 2
; CHECK-NEXT:    and64 r1, r2
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    mov64 r1, r0
; CHECK-NEXT:    rsh64 r1, 4
; CHECK-NEXT:    add64 r0, r1
; CHECK-NEXT:    lddw r1, 1085102592571150095
; CHECK-NEXT:    and64 r0, r1
; CHECK-NEXT:    lddw r1, 72340172838076673
; CHECK-NEXT:    mul64 r0, r1
; CHECK-NEXT:    rsh64 r0, 56
; CHECK-NEXT:    ja LBB7_3
; CHECK-NEXT:  LBB7_1:
; CHECK-NEXT:    mov64 r0, 64
; CHECK-NEXT:  LBB7_3: # %cond.end
; CHECK-NEXT:    exit
    %ret = call i64 @llvm.ctlz.i64(i64 %a, i1 0)
    ret i64 %ret
}
