; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=sbf | FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -march=sbf -mcpu=v3 -mattr=+alu32 | FileCheck %s --check-prefix=CHECK-ALU32

define i64 @bar(i64 %a, i64 %b) {
; CHECK-LABEL: bar:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    call foo
; CHECK-NEXT:    add64 r1, r0
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    exit
;
; CHECK-ALU32-LABEL: bar:
; CHECK-ALU32:       # %bb.0: # %entry
; CHECK-ALU32-NEXT:    call foo
; CHECK-ALU32-NEXT:    add64 r1, r0
; CHECK-ALU32-NEXT:    mov64 r0, r1
; CHECK-ALU32-NEXT:    exit
entry:
    %c = call i128 @foo(i64 %a, i64 %b)
    %d = lshr i128 %c, 64
    %e = trunc i128 %d to i64
    %f = trunc i128 %c to i64
    %g = add i64 %e, %f
    ret i64 %g
}


define i128 @foo(i64 %a, i64 %b) {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov64 r0, r1
; CHECK-NEXT:    add64 r0, r2
; CHECK-NEXT:    mov64 r3, 1
; CHECK-NEXT:    jlt r0, r1, LBB1_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    mov64 r3, 0
; CHECK-NEXT:  LBB1_2: # %entry
; CHECK-NEXT:    arsh64 r2, 63
; CHECK-NEXT:    arsh64 r1, 63
; CHECK-NEXT:    add64 r1, r2
; CHECK-NEXT:    add64 r1, r3
; CHECK-NEXT:    exit
;
; CHECK-ALU32-LABEL: foo:
; CHECK-ALU32:       # %bb.0: # %entry
; CHECK-ALU32-NEXT:    mov64 r0, r1
; CHECK-ALU32-NEXT:    add64 r0, r2
; CHECK-ALU32-NEXT:    mov32 w3, 1
; CHECK-ALU32-NEXT:    jlt r0, r1, LBB1_2
; CHECK-ALU32-NEXT:  # %bb.1: # %entry
; CHECK-ALU32-NEXT:    mov32 w3, 0
; CHECK-ALU32-NEXT:  LBB1_2: # %entry
; CHECK-ALU32-NEXT:    arsh64 r2, 63
; CHECK-ALU32-NEXT:    arsh64 r1, 63
; CHECK-ALU32-NEXT:    add64 r1, r2
; CHECK-ALU32-NEXT:    mov32 r2, w3
; CHECK-ALU32-NEXT:    add64 r1, r2
; CHECK-ALU32-NEXT:    exit
entry:
    %a1 = sext i64 %a to i128
    %b1 = sext i64 %b to i128
    %c = add i128 %a1, %b1
    ret i128 %c
}
