; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=sbf -mcpu=v3 -o - %s | FileCheck %s


; __rustc::rust_begin_unwind
; Function Attrs: nofree norecurse noreturn nosync nounwind memory(none)
define hidden void @_RNvCs6GJaa0HwATA_7___rustc17rust_begin_unwind(ptr noalias noundef readonly align 8 captures(none) dereferenceable(24) %_info) unnamed_addr #0 {
; CHECK-LABEL: _RNvCs6GJaa0HwATA_7___rustc17rust_begin_unwind:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:  .LBB0_1: # %bb1
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ja .LBB0_1
start:
  br label %bb1

bb1:                                              ; preds = %bb1, %start
  br label %bb1
}

; Function Attrs: nounwind
define noundef range(i64 0, 2) i64 @entrypoint(ptr noundef readnone captures(none) %_input) unnamed_addr #1 {
; CHECK-LABEL: entrypoint:
; CHECK:       # %bb.0: # %start
; CHECK-NEXT:    lddw r1, -2401053088876216593
; CHECK-NEXT:    stxdw [r10 - 4096], r1
; CHECK-NEXT:    mov64 r1, r10
; CHECK-NEXT:    add64 r1, -4096
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ldxdw r6, [r10 - 4096]
; CHECK-NEXT:    lddw r1, 4611686018427387904
; CHECK-NEXT:    stxdw [r10 - 4096], r1
; CHECK-NEXT:    mov64 r1, r10
; CHECK-NEXT:    add64 r1, -4096
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ldxdw r1, [r10 - 4096]
; CHECK-NEXT:    lddw r2, 4613937818241073152
; CHECK-NEXT:    stxdw [r10 - 4096], r2
; CHECK-NEXT:    mov64 r2, r10
; CHECK-NEXT:    add64 r2, -4096
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    ldxdw r2, [r10 - 4096]
; CHECK-NEXT:    call __ltdf2
; CHECK-NEXT:    rsh64 r0, 63
; CHECK-NEXT:    and64 r6, r0
; CHECK-NEXT:    mov64 r0, r6
; CHECK-NEXT:    exit
start:
  %0 = alloca [8 x i8], align 8
  %1 = alloca [8 x i8], align 8
  %2 = alloca [8 x i8], align 8
  call void @llvm.lifetime.start.p0(ptr nonnull %2)
  store i64 -2401053088876216593, ptr %2, align 8
  call void asm sideeffect "", "r,~{memory}"(ptr nonnull %2) #3, !srcloc !2
  %x = load i64, ptr %2, align 8, !noundef !3
  call void @llvm.lifetime.end.p0(ptr nonnull %2)
  call void @llvm.lifetime.start.p0(ptr nonnull %1)
  store double 2.000000e+00, ptr %1, align 8
  call void asm sideeffect "", "r,~{memory}"(ptr nonnull %1) #3, !srcloc !2
  %a = load double, ptr %1, align 8, !noundef !3
  call void @llvm.lifetime.end.p0(ptr nonnull %1)
  call void @llvm.lifetime.start.p0(ptr nonnull %0)
  store double 3.000000e+00, ptr %0, align 8
  call void asm sideeffect "", "r,~{memory}"(ptr nonnull %0) #3, !srcloc !2
  %b = load double, ptr %0, align 8, !noundef !3
  call void @llvm.lifetime.end.p0(ptr nonnull %0)
  %_5 = fcmp olt double %a, %b
  %3 = and i64 %x, 1
  %_0.sroa.0.0 = select i1 %_5, i64 %3, i64 0
  ret i64 %_0.sroa.0.0
}

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p0(ptr captures(none)) #2

; Function Attrs: mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p0(ptr captures(none)) #2

attributes #0 = { nofree norecurse noreturn nosync nounwind memory(none) "target-cpu"="v3" "target-features"="+static-syscalls" }
attributes #1 = { nounwind "target-cpu"="v3" "target-features"="+static-syscalls" }
attributes #2 = { mustprogress nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #3 = { nounwind }

!llvm.module.flags = !{!0}
!llvm.ident = !{!1}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{!"rustc version 1.95.0-dev (ae660768a 2026-08-17)"}
!2 = !{i64 894521428880749}
!3 = !{}
