; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=sbf | FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -march=sbf -mcpu=v3 -mattr=+alu32 | FileCheck %s --check-prefix=CHECK-ALU32

; Function Attrs: nounwind uwtable
define { i64, i32 } @foo(i32 %a, i32 %b, i32 %c) #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov64 r4, 1
; CHECK-NEXT:    mov64 r5, 2
; CHECK-NEXT:    call bar
; CHECK-NEXT:    exit
;
; CHECK-ALU32-LABEL: foo:
; CHECK-ALU32:       # %bb.0: # %entry
; CHECK-ALU32-NEXT:    mov32 w4, 1
; CHECK-ALU32-NEXT:    mov32 w5, 2
; CHECK-ALU32-NEXT:    call bar
; CHECK-ALU32-NEXT:    exit
entry:
  %call = tail call { i64, i32 } @bar(i32 %a, i32 %b, i32 %c, i32 1, i32 2) #3
  ret { i64, i32 } %call
}

declare { i64, i32 } @bar(i32, i32, i32, i32, i32) #1
