; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -march=sbf -mcpu=v3 | FileCheck %s --check-prefix=CHECK
; RUN: llc < %s -march=sbf -mcpu=v3 -mattr=+alu32 | FileCheck %s --check-prefix=CHECK-ALU32

; Function Attrs: nounwind uwtable
define { i128, i128 } @foo(i32 %a, i32 %b, i32 %c) #0 {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mov64 r6, r1
; CHECK-NEXT:    stdw [r10 + 0], 2
; CHECK-NEXT:    mov64 r1, r10
; CHECK-NEXT:    add64 r1, -4096
; CHECK-NEXT:    mov64 r5, 1
; CHECK-NEXT:    call bar
; CHECK-NEXT:    ldxdw r1, [r10 - 4088]
; CHECK-NEXT:    ldxdw r2, [r10 - 4096]
; CHECK-NEXT:    ldxdw r3, [r10 - 4072]
; CHECK-NEXT:    ldxdw r4, [r10 - 4080]
; CHECK-NEXT:    stxdw [r6 + 16], r4
; CHECK-NEXT:    stxdw [r6 + 24], r3
; CHECK-NEXT:    stxdw [r6 + 0], r2
; CHECK-NEXT:    stxdw [r6 + 8], r1
; CHECK-NEXT:    exit
;
; CHECK-ALU32-LABEL: foo:
; CHECK-ALU32:       # %bb.0: # %entry
; CHECK-ALU32-NEXT:    mov64 r6, r1
; CHECK-ALU32-NEXT:    stw [r10 + 0], 2
; CHECK-ALU32-NEXT:    mov64 r1, r10
; CHECK-ALU32-NEXT:    add64 r1, -4096
; CHECK-ALU32-NEXT:    mov32 w5, 1
; CHECK-ALU32-NEXT:    call bar
; CHECK-ALU32-NEXT:    ldxdw r1, [r10 - 4088]
; CHECK-ALU32-NEXT:    ldxdw r2, [r10 - 4096]
; CHECK-ALU32-NEXT:    ldxdw r3, [r10 - 4072]
; CHECK-ALU32-NEXT:    ldxdw r4, [r10 - 4080]
; CHECK-ALU32-NEXT:    stxdw [r6 + 16], r4
; CHECK-ALU32-NEXT:    stxdw [r6 + 24], r3
; CHECK-ALU32-NEXT:    stxdw [r6 + 0], r2
; CHECK-ALU32-NEXT:    stxdw [r6 + 8], r1
; CHECK-ALU32-NEXT:    exit
entry:
  %call = tail call { i128, i128 } @bar(i32 %a, i32 %b, i32 %c, i32 1, i32 2) #3
  ret { i128, i128 } %call
}

declare { i128, i128 } @bar(i32, i32, i32, i32, i32) #1
